---
title: Title of my thesis
subtitle: Some subtitle for my thesis
authors:
  - name: Johan Ulstrup
    affiliation: Aarhus University
    roles: writing
    corresponding: true
keywords:
  - Vestibulum
  - Nunc ac dignissim 
  - Proin feugiat 
plain-language-summary: |
  In plain language, the thesis describes an analysis of something. Somethings was not previously know. I found something and was able to conclude something. The perspectives of this result is something.
key-points:
  - Proin tempor lorem arcu, at condimentum purus volutpat eu. 
  - Mauris cursus laoreet ex, ignissim bibendum est posuere iaculis.
  - Nam vel neque eu arcu blandit fringilla et in quam.
date: last-modified
date-format: long
degree: Master of Science in Bioinformatics
---

# DNA language models are powerful predictors of genome-wide
variant effects

A recent study published in the Proceedings of the National Academy of Sciences introduces the Genomic Pre-trained Network (GPN), a model designed to predict genome-wide variant effects through unsupervised pretraining on genomic DNA sequences. The researchers trained GPN using unaligned reference genomes of Arabidopsis thaliana and seven related species within the Brassicales order. GPN successfully learned gene structures and DNA motifs without supervision and outperformed traditional conservation-based predictors like phyloP and phastCons. The model's predictions for A. thaliana are accessible as sequence logos in the UCSC Genome Browser. Additionally, the authors have made the code publicly available, enabling the training of GPN for any species using its DNA sequence alone, facilitating unsupervised prediction of variant effects across entire genomes

[@Kantorovitz2024]. 



# Bon mot

> Nothing in Biology Makes Sense except in the Light of Evolution
>
> \- Theodosius Dobzhansky


# References

::: {#refs}
:::
